### ISSUE TITLE
cmd/govim: exiting insert mode via escape flickers back to insert mode

### ISSUE THREAD

**Issue by mvdan** [myitcv/govim#152]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>

$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 18 2019 00:13:33)
Included patches: 1-1183
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl/dyn
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl/dyn          +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     

</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +33e5da48d5 Wed Apr 17 00:05:41 2019 +0000 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/mvdan/go/bin"
GOCACHE="/home/mvdan/go/cache"
GOEXE=""
GOFLAGS="-ldflags=-w"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/mvdan/go"
GOPROXY=""
GORACE=""
GOROOT="/home/mvdan/tip"
GOTMPDIR=""
GOTOOLDIR="/home/mvdan/tip/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build601160762=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What version/commit of `govim` are you using?

3317c0b13d1f2e09057e3ef13bdcf538cef14640

### How did you install `govim`?

Vim 8 package.

### What did you do?

Install govim and start `vim` on any file. Happens on both a new file outside a module, and a Go file inside a module.

### What did you expect to see?

When I press escape to exit insert mode, it just does that.

### What did you see instead?

The cursor goes left and exits insert mode, then goes back to the right into insert mode for ~200ms, and then back left out of insert mode.

This can be reproduced even if I empty my vimrc and delete all packages other than govim.

**Comment by myitcv** [comment]
Per our Slack exchange, this is very strange. 

I'm not seeing this, and have never seen this. So my guess is that there is something about your setup that `govim` is not accounting for (and honestly it could be something like terminal type/configuration), and the two are therefore interacting badly. What's very bizarre is that you see this from a minimal setup.

Just to confirm before going any further, do you see this when loading `vim` without a file argument? i.e. just a plain buffer? Then entering insert mode to make a change etc?

If you were able to try this with `gvim` that would be an interesting experiment (but I realise that is a non-zero cost in terms of recompiling `gvim`).

The two most likely things from a `govim` perspective are:

* the viewport code
* the quickfix code

If you're able to, with a minimal setup, i.e. only `govim` as the plugin, minimal `.vimrc`:

* first disable the viewport code by commenting this line

https://github.com/myitcv/govim/blob/5716980de9287a48b59fdf48f78a7fdd0725ab72/plugin/govim.vim#L105

* second disable the quickfix updating by commenting this line

https://github.com/myitcv/govim/blob/5716980de9287a48b59fdf48f78a7fdd0725ab72/cmd/govim/main.go#L152

When it comes to updating the Go code (wherever you have installed `govim`) you will need to start `vim`/`gvim` via:

```
GOVIM_ALWAYS_INSTALL=true vim
```

to force the re-installation of `govim`.

If you could try the various permutations of the above that will help. Furthermore, if you could try this by simple opening `vim` _without_ a file argument, so that it just starts with an empty buffer. Because by so doing we can rule out any of the code associated with `*.go` specific buffers.

Perhaps in conjunction with this test you might also enable the Vim channel logs by uncommenting the following line:

https://github.com/myitcv/govim/blob/5716980de9287a48b59fdf48f78a7fdd0725ab72/plugin/govim.vim#L2

You can then `tail -f` this file and see what's happening around the time of first pressing escape.

Finally, I just spotted the following in the Vim issue tracker:

https://github.com/vim/vim/issues/4269

It might be worth looking at key mappings next (but with a minimal Vim setup I'm guessing this is less likely)

Thanks for being patient with `govim` :)

**Comment by myitcv** [comment]
Ok I _think_ I've tracked this down.

There are two things going on here:

* firstly there was some bad logic and I was likely using the wrong method for populated the quickfix errors list. Both are fixed in https://github.com/myitcv/govim/pull/153
* secondly, there appears to be either a Vim issue here: I've raised that as https://github.com/vim/vim/issues/4278

**Comment by myitcv** [comment]
Per our Slack conversation I think this issue is now fixed by adding the following to your `.vimrc`:

```
set timeoutlen=1000 ttimeoutlen=0
```

More details in the wiki:

https://github.com/myitcv/govim/wiki/vimrc-tips#-fix-why-does-vim-flicker-when-i-enter-normal-mode-leave-exit-insert-mode

The Vim issue that I reference above is, it seems, unrelated. Hence I've created https://github.com/myitcv/govim/issues/203 to track that issue.
